### ISSUE TITLE
[FEATURE] Sync a board with a github project board

### ISSUE THREAD

**Issue by franklevasseur** [linear/linear#117]
Hi,

I'm not sure this is the right repo to open an issue on, but if it's not, please show me how I can make a feature request / suggestion.

Allright, I've been using [Github project boards](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) and I was wondering if there was any way to synchronize these with boards on Linear. 

I'd probably want to use my existing Github boards as they currently are and slowly gradually move my stuff to Linear and make a more "complete" use of the app (when creating new boards for instance).

I feel like this would be a really nice touch, specially for a developper focused tool that already offers some level of integration with Github. 

Keep in mind that most developpers don't get to choose which "issue tracking / project management" tool they use and this would be a really nice selling points for dev to adopt Linear. 

Anyway, let me know if this is currently doable with the app as it is or if its a feature you plan on adding anytime soon.

François

**Comment by rlargman** [comment]
You could try setting up Zapier to sync from GitHub to Linear as both GitHub and Linear have integrations with Zapier.

For non-Zapier solutions, you could use the Migration Assistant tool (in Settings --> Import/export) periodically for fresh issues, but that will likely be a pain as it's manual. You could alternatively modify the code for the CLI importer tool in this repo, adding a filter for when the issue was created (createdAt on the Issue object: https://docs.github.com/en/graphql/reference/objects#issue), and then have that run as a script periodically.

I've also seen this tool mentioned before, and it might help you out: https://linear-sync.com/

Also feel free to join our [Slack community](http://linear.app/join-slack) for future questions, where you can probably get help a bit faster.

**Comment by franklevasseur** [comment]
Thanks a lot for the answer, I'll take a look a those links.

François
