### ISSUE TITLE
Images, videos, gifs as markdown in Issue description

### ISSUE THREAD

**Issue by irealva** [linear/linear#145]
I'm trying to use markdown to show a preview of an image, video, or gif as occurs when you drag and drop it into an Issue.

Seems like [this should work but it doesn't](https://github.com/linear/linear/blob/bc39d23af232f9fdbe7df458b0aaa9554ca83c57/packages/sdk/src/_tests/readme.test.ts#L253), even when the file has been uploaded to Linear: `![assetName](assetUrl)`. Is this possible?

**Comment by rlargman** [comment]
@irealva that should work. Can you provide an example of a query that is failing to properly upload an image using that method?

Also, I would recommend you join [our Slack community](http://linear.app/join-slack) and post in the #api channel for faster responses.

**Comment by rlargman** [comment]
For future reference, the Slack thread where this is being discussed: https://linearcustomers.slack.com/archives/CN61HRZ9T/p1630619109022800

**Comment by vpontis** [comment]
Hi Raissa (@rlargman)! I'm trying to make a mini iOS app where I can take a screenshot and then share to the app to automatically create a Linear issue. 

I'm running into the same issue here where I'm uploading an image to Linear's CDN but then Linear returns an empty description string when I create the issue. I can't load the Slack conversation since Slack only stores the last 90 days of conversations.
