### ISSUE TITLE
Feature request: symetric sync of issues with github

### ISSUE THREAD

**Issue by Aarbel** [linear/linear#227]
Hi Linear team.

It would be amazing to be able to sync issues between Linear and Github Repo (with contents, labels, etc..).

How can we achieve that ? Thanks a lot

**Comment by guillaumelachaud** [comment]
Hi!

For now, it is not possible to achieve a symmetric sync as the importer only works 1-way, to import your Github issues into Linear. 
In order to sync back issues to Github, you could use the export feature from Linear. 

There is no automatic way to achieve this today but we'll keep your request for future consideration!

**Comment by Aarbel** [comment]
@guillaumelachaud it would be very usefull, has we also have the history of issues in github when we use Linear

**Comment by newbish** [comment]
This is why we have been unwilling to try Linear at our company.

**Comment by Aarbel** [comment]
We just left Linear because of that 👋 Hope that github projects will recruit Linear team 😇

**Comment by tommoor** [comment]
Hey folks, we're soft launching this feature today – infact this comment was written from within Linear ;)

You can check out the [docs for how to setup here](https://linear.app/docs/github#github-issue-syncing).
