### ISSUE TITLE
Getting rate limited even when authenticated via oAuth2

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [linear/linear#302]
So I'm making an integration for my app and the requests are constantly being rate limited even though the documentation says that `Query complexity = 200,000` for oAuth Apps.

this is the query I'm making

```gql
query Query {
  issues { 
   edges {
     node {
       title
       description
       creator {
         email
       }
       labels {
         edges {
           node {
             name
           }
         }
       }
      assignee {
        email
      }
       comments {
         edges {
           node {
             user {
               email
             }
             body
           }
         }
       }
     }
   }
  }
}

```

the error says `query too complex, query is 13,415 of complexity, max 10,000`; I understand that said limit (10,000) is for unauthenticated requests, however as I said I have an integration and I'm authorizing the user with linear's oAuth protocol

**Comment by guillaumelachaud** [comment]
Hi! @AlvaroAquijeDiaz 

You are right that requests that are authenticated with oAuth can use up to 200,000 complexity points per hour. 
But we also enforce a per-request limit of 10,000 points as per the [documentation](https://developers.linear.app/docs/graphql/working-with-the-graphql-api/rate-limiting#maximum-complexity-of-a-single-query)

I invite you to simplify your query in order to go below the limit of 10,000 complexity points.

**Comment by AlvaroAquijeDiaz** [comment]
Ah my bad, didn't noticed that part of the docs, thanks
