### ISSUE TITLE
Image import problem

### ISSUE THREAD

**Issue by sintanial** [linear/linear#429]
When i try to import issues from one linear account to another by linear cli tool, i receive error with importing images

```
Failed to replace image Unsupported file type 68bf87bb-da0c-4520-b32f-32a311941b64
Failed to replace image Unsupported file type de7505e9-ef77-414d-b7f4-b74328cee039
Failed to replace image Unsupported file type 0247ef6b-5b20-4911-ade4-3c2d60dae391
Failed to replace image Unsupported file type a9441f2b-2086-4736-86d8-e98d253d504f
```

I guess problem with images inserted from clipboard into issue without file extension )). !

**Comment by guillaumelachaud** [comment]
Hi @sintanial 

It turns out that the issue is not in the CLI importer but in the Linear export CSV file. We used to export the CSV file without signing the assets URLs. When the CLI importer attempted to download these, it failed with the above error.

In order to workaround this problem, you will have to redownload the CSV export form Linear. It will now contains signed URLs valid for 30 days. These should get imported without any issues.

Let me know if you still need help!
