### ISSUE TITLE
Gitlab integration stopped working

### ISSUE THREAD

**Issue by danieldanciu** [linear/linear#530]
We are using the GitLab integration plugin to update Linear issues from GitLab(https://linear.app/integrations/gitlab). This worked like a breeze for roughly 2 years, but it suddenly stopped working a few days ago. 
When I check the Gitlab webhook, Linear seems to happily return a 200 OK with every GitLab request, but the Linear issue itself doesn't get updated when e.g. adding a text such as `Fixes SW-3904` to the Merge Request description.

**Comment by danieldanciu** [comment]
We are still experiencing a broken gitlab/linear integration. I see the task being marked as completed. Was the fix actually pushed already? If not, what's the best way to track the status?

**Comment by mufeez-amjad** [comment]
Hi @danieldanciu, I apologize for not closing the loop.

We had a number of similar reports about GitLab suddenly not working. The reason was because GitLab added an expiry date of May 14th 2024 for all tokens that had no expiry-date previously. Blog post [here](https://about.gitlab.com/blog/2023/10/25/access-token-lifetime-limits/#our-decision-to-remove-support-for-non-expiring-access-tokens). 

You reported that your integration stopped working on the 16th, so you should fall under this change. To continue, you'll need to re-install the GitLab integration. 

Please reach out if you're still having issues, thanks!

**Comment by danieldanciu** [comment]
This worked, thank you for your help!
