### ISSUE TITLE
[Jira csv importer] Information about EPIC are not kept

### ISSUE THREAD

**Issue by maxime-fender** [linear/linear#570]
Hello :slightly_smiling_face: 

I am using the JIRA csv importer and it seems that EPIC are converted into projects in Linear. The issue is that information about the EPIC does not seem to be kept, in particular the if the EPIC is marked as `Done` in Jira, I would like to import it as `Completed` in Linear. This would enable to auto-archive old projects (old epics).

Thanks for your help !

**Comment by guillaumelachaud** [comment]
Hi!

The Jira CSV importer in the CLI importer does not support importing Epics as projects. So I am assuming your request is for the in-app Jira CSV importer. 

I have filed a new issue internally and will close this one as this repo is only meant to report CLI and SDK issues. Feel free to contact support in Linear so that you can be kept up to date of the progress.
